branches:
        only:
        - test-branch
matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_script:
        - cd server
      cache:
        directories:
          - "$HOME/.m2/repository"
      script:
        - mvn clean verify
      before_deploy:
       - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
       - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      deploy:
        provider: script
        skip_cleanup: true
        script: bash ../scripts/deployMaven.sh
        on:
          branch: test-branch
      after_deploy:
        - cd  ../scripts
        - ./deployP2.sh
      addons:
        apt:
          packages:
            - libxml2-utils

    - language: node_js
      node_js:
        - "8"
      before_script:
        - cd client
      cache:
        yarn: true
        directories:
          - node_modules
      before_deploy:
      - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - yarn
    
      deploy:
        provider: script
        script: bash ../scripts/deployNPM.sh
        on:
          branch: test-branch
        skip_cleanup: true
